---

- name: Write EC2 Private Key to File
  copy:
     content: "{{ keypair_results.key.private_key }}"
     dest: "{{ aws.private_key_file }}"
#  when: "{{ wordpass_keypair.changed }}"
  
- name: Write EC2 WordPress Specs to File
  copy:
    content: "{{ ec2_wordpress_instance }}"
    dest: "/tmp/{{ s3.server_specs.object }}"
#  when: "{{ not ec2_wordpress|skipped }}"

- name: Put EC2 WordPress Specs into S3
  s3:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    bucket: "{{ s3.server_specs.bucket }}"
    object: "{{ s3.server_specs.object }}"
    src: "/tmp/{{ s3.server_specs.object }}"
    mode: put
#  when: "{{ not ec2_wordpress|skipped }}"
