---


- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- include: roles/wordpress/tasks/dependency.yml

- name: Install RHEL Docker
  yum:
    name: docker
    enablerepo: rhui-REGION-rhel-server-extras,rhui-REGION-rhel-server-optional
    state: latest

#- name: Add Docker config
#  copy:
#    src: docker
#    dest: /etc/sysconfig/docker
#    owner: root
#    group: root
#    mode: 0644

- name: Start and Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Isntall MariaDB for WordPress
  docker_container:
    name: wordpress-db
    image: mariadb
    state: started
    env:
      MYSQL_ROOT_PASSWORD: password
   

- name: Install WordPress Docker Container
  docker_container:
    name: wordpress-server
    image: wordpress
    state: started
    links: 
      - wordpress-db:mysql
    ports:
      - 8080:80
