---

- name: Install Dependendies
  include_role:
    name: common
    tasks_from: dependency
  tags:
    - docker
    - wordpress
    - wordpress-db

- name: Install RHEL Docker
  yum:
    name: docker
    enablerepo: rhui-REGION-rhel-server-extras,rhui-REGION-rhel-server-optional
    state: latest
  tags:
    - docker
    - wordpress
    - wordpress-db

- name: Start and Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
    - wordpress
    - wordpress-db

- name: Install and Start the WordPress-Database Docker Container
  docker_container:
    name: "{{ wordpress_db.container_name }}"
    image: "{{ wordpress_db.container_image }}"
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ secrets.mysql_root_password }}"
  tags:
    - docker
    - wordpress-db
    - wordpress-db-start

- name: Install and Start the WordPress-Server Docker Container
  docker_container:
    name: "{{ wordpress.container_name }}"
    image: "{{ wordpress.container_image }}"
    state: started
    links: 
      - "{{ wordpress_db.container_name }}:mysql"
    ports: "{{ wordpress.ports }}"
  tags:
    - docker
    - wordpress
    - wordpress-start
