---

- name: Create AWS Keypair
  ec2_key:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    name: wordpass-kp
    state: present
    region: us-west-2
  register: wordpass_keypair
  tags:
    - kp

- name: Write Private Key
  copy:
     content: "{{ wordpass_keypair.key.private_key }}"
     dest: "{{ pk }}"
     #mode: 0600
  when: "{{ wordpass_keypair.changed }}"
  tags:
    - kp

- name: Check if WordPress Instance file Exists and Download
  s3:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    bucket: server-specs
    object: /wordpress_instance
    dest: /tmp/wordpress_instance
    mode: get
  register: s3_results
  ignore_errors: True
  tags:
    - test

- name: Load the file
  include_vars: /tmp/wordpress_instance
  when: "not {{ s3_results|failed }}"

- name: Does instance exist?
  ec2_remote_facts:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    filters:
      instance-id: "{{ instance_ids[0] }}"
    region: us-west-2
  when: "{{ instance_ids[0] is defined }}"
  register: facts
  tags:
    - testing

- name: Launch EC2 Instance for WordPress
  ec2:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    key_name: wordpass-kp
    instance_type: "{{ ec2.instance_type }}"
    image: "{{ ec2.image }}"
    wait: "{{ ec2.wait }}"
    count: "{{ ec2.count }}"
    instance_tags: "{{ ec2.instance_tags }}"
    assign_public_ip: "{{ ec2.assign_public_ip }}"
    vpc_subnet_id: subnet-96b152cd
    volumes: "{{ ec2.volumes }}"
    group: test
    region: us-west-2
  when:
    - "{{ facts|skipped or facts.instances[0].state in ['terminated', 'shutting-down']}}"
  register: ec2_wordpress
  tags:
    - ec2

- name: Write Specs to File
  local_action: copy
  args:
    content: "{{ ec2_wordpress }}"
    dest: /tmp/wordpress_instance
  when: "{{ not ec2_wordpress|skipped }}"
  tags:
    - ec2

- name: Put EC2 WordPress Specs into S3
  s3:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    bucket: server-specs
    object: wordpress_instance
    src: /tmp/wordpress_instance
    mode: put
  when: "{{ not ec2_wordpress|skipped }}"
  tags:
    - ec2
  
- name: Load the file
  include_vars: /tmp/wordpress_instance

- name: Waiting on SSH
  local_action: wait_for
  args:
    host: "{{ instances[0].private_ip }}"
    port: 22
    timeout: 300
    state: started

- name: Adding IP of newly created instance to inventory
  local_action: add_host
  args:
    name: "{{ instances[0].private_ip }}"
    group: "wordpress-server"
 
#- name: Install Docker on WordPress EC2
#  docker_container:
#    name: wordpress-server
#    image: wordpress
#    state: started
#  delegate_to: "{{ instances[0].private_ip }}"


#- name: Install WordPress Docker Server
#  debug:
#    msg: "{{ instances[0] }}"
