---

- name: Create the S3 Bucket for Persistent EC2 Instance Specs
  s3_bucket:
    aws_access_key: "{{ aws.aws_access_key }}"
    aws_secret_key: "{{ aws.aws_secret_key }}"
    name: "{{ s3.server_specs.bucket }}"
