---

- name: Install EPEL Repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install Python-Pip
  yum:
    name: python-pip
    state: present
  
- name: Install Boto
  pip:
    name: boto
    state: present

- name: Install Docker-Py
  pip:
    name: docker-py
    state: present
